# Redirect with a 301
[[redirects]]
from = "/#home"
to = "/"
status = 301

# Redirect with a 302
[[redirects]]
from = "/#about"
to = "/"
status = 302

# Show a custom 404 for this path
[[redirects]]
from = "/"
to = "https://wa.me/918008844558"
status = 404